[WIP] general: Convert from base HTML/CSS/JS to Next.js
kata-containers/kata-containers.github.io pull request #16
Opened 2024-10-21 00:39 UTC by a1icja

**tl;dr** - The dashboard has been rebuilt using Next.js, TailwindCSS, and PrimeReact (components library) to provide a better overall user and developer experience.

---

This PR reimplements the features found in the dashboard using Next.js. It is not intended to be used for adding new features or fixing old bugs.

Please see the `README.md` file included in this PR for a general overview of how the project is formatted as well as information for how to setup a development environment.

*A live version of this dashboard with additional improvements and features (coming in future PRs) can be found [here](https://a1icja.github.io/kata-dashboard-next/).*

---

In order for this PR to be merged successfully, a couple things must happen:

1. The [GitHub Pages settings for this repository](https://github.com/kata-containers/kata-containers.github.io/settings/pages) must be changed to [use GitHub Actions as the source.](https://github.com/user-attachments/assets/7d89c131-f337-4fea-bb79-cc3f1bb7b8f7)
2. The "Fetch CI Nightly Data" action must be run manually **once** *following* this PR being merged

---

Due to the significant changes present in this PR, please review each file carefully.

2024-10-21 15:00 UTC, afinn12 commented on .github/workflows/fetch-ci-nightly-data.yaml
> -          # back out whatever data was there
Might want to leave in.

2024-10-21 21:29 UTC, a1icja commented on .github/workflows/fetch-ci-nightly-data.yaml
> -          # back out whatever data was there
Could go either way. Anna and I talked, and it would be helpful to leave in to reduce the number of commits, but there is the case where it could break on a newly created branch. Might be helpful to do a check and run only if commits exist. Food for thought

2024-10-23 00:37 UTC, Redent0r commented on scripts/fetch-ci-nightly-data.js
> +var ci_nightly_runs_url =
Why not use `const` for all these?

2024-10-23 00:41 UTC, a1icja commented on scripts/fetch-ci-nightly-data.js
> +var ci_nightly_runs_url =
Definitely a change we can make! The use of `var` came from the current version of the script.

2024-10-23 00:50 UTC, Redent0r commented on pages/index.js
> +        console.error("Error fetching data:", error);
May consider showing some kind of toast or popup for the user in case they don't check the console

2024-10-23 14:38 UTC, arc9693 commented on pages/index.js
> +      fails: job.fails,
Might wanna use [spread operator](https://www.w3schools.com/react/react_es6_spread.asp) to avoid rewriting assignments.

2024-10-23 14:38 UTC, arc9693 commented on pages/index.js
> +        });
This logic can be moved out of this file. Could use a const var for url.

2024-10-23 14:38 UTC, arc9693 commented on pages/index.js
> +  };
This could become another react component?

2024-10-27 14:21 UTC, a1icja commented on pages/index.js
> +        });
Definitely can move this out, but I don't quite follow the const var idea. Could you elaborate?

2024-10-27 14:29 UTC, a1icja commented on scripts/fetch-ci-nightly-data.js
> +var ci_nightly_runs_url =
Changed in [e9c0fcb](https://github.com/kata-containers/kata-containers.github.io/pull/16/commits/e9c0fcbe6fff61b17c6cd8e4b9456bcbeae09f06)

2024-10-27 14:29 UTC, a1icja commented on pages/index.js
> +        console.error("Error fetching data:", error);
Added a TODO comment for this since this PR isn't meant to add new features. When @sprt gets back, we can add it to the project board.

2024-10-27 14:30 UTC, a1icja commented on pages/index.js
> +      fails: job.fails,
Changed in [5ed8858](https://github.com/kata-containers/kata-containers.github.io/pull/16/commits/5ed8858ca27efc8288386a941d4aa817aad7e7d4)

2024-10-27 14:30 UTC, a1icja commented on pages/index.js
> +  };
Changed in [f61c5df](https://github.com/kata-containers/kata-containers.github.io/pull/16/commits/f61c5dfd1883336588c366e8990a4abf2f75fcc1)

2024-10-29 20:35 UTC, sprt requested changes
Thank you @a1icja and team! I left a few comments.

One ask - if you scroll down to the bottom of the PR page, you'll find that we're failing the [commit message check](https://github.com/kata-containers/kata-containers.github.io/actions/runs/11541292791/job/32175373802?pr=16). Can you follow the [contributing guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format) (the whole section up until *Reviews*, not just the first heading) and fix your PR? TLDR: Squash your commits into one, update the commit subject to match the new PR title, add a description and a signoff.

One question - do you know how hard it would be to be able to set up a staging website per PR to be able to test PRs publicly before merging them? Otherwise folks would have to manually checkout feature branches to test changes.

2024-10-29 20:35 UTC, sprt commented on .github/workflows/fetch-ci-nightly-data.yaml
> -          # back out whatever data was there
Let's revert this so we minimize the number of changes we make and reduce the risk of breaking something.

2024-10-29 20:35 UTC, sprt commented on .github/workflows/fetch-ci-nightly-data.yaml
> +          rm -rf data/
In this redundant if we already call `git rm`? We could also revert these 2 new lines to keep things simple.

2024-10-29 20:35 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +      // console.log('checks_request', checks_request);
```suggestion
```

2024-10-29 20:35 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +    // commit_sha: pr["merge_commit_sha"],  // For getting checks run on main branch after merge
```suggestion
```

2024-10-29 20:35 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +  // console.log('required jobs: ', required_jobs);
```suggestion
```

2024-10-29 20:35 UTC, sprt commented on .github/workflows/deploy.yml
> +# Sample workflow for building and deploying a Next.js site to GitHub Pages
Adding a link to the original for reference.
```suggestion
# Reference: https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml

# Sample workflow for building and deploying a Next.js site to GitHub Pages
```

2024-10-29 20:35 UTC, sprt commented on README.md
> +- **npm** (comes with Node.js)
nit: Could we link to installation instructions here?

2024-10-29 20:35 UTC, sprt commented on README.md
> +   ```
Could we add full instructions on how to test this e2e locally? If I run that command, it simply prints the API results to the console, but the dashboard is still empty. We need to have instructions so that anyone can set up a working dashboard locally and iterate.

2024-10-30 23:00 UTC, a1icja commented on .github/workflows/fetch-ci-nightly-data.yaml
> +          rm -rf data/
It's "redundant", but I had to add it in order to ensure that the data is always replaced on update.

2024-10-30 23:01 UTC, a1icja commented on README.md
> +- **npm** (comes with Node.js)
Can do! I'm partial to [fnm](https://github.com/Schniz/fnm), but I can also do the official instructions if you'd like.

2024-10-31 13:11 UTC, sprt commented on README.md
> +- **npm** (comes with Node.js)
We can just link to https://nodejs.org/en/download - folks can choose the installer they prefer

2024-10-31 13:14 UTC, sprt commented on .github/workflows/fetch-ci-nightly-data.yaml
> +          rm -rf data/
Could you explain further?

2024-11-03 21:37 UTC, a1icja commented on README.md
> +- **npm** (comes with Node.js)
Implemented

2024-11-03 21:37 UTC, a1icja commented on README.md
> +   ```
Instructions updated

2024-11-03 21:37 UTC, a1icja commented on .github/workflows/fetch-ci-nightly-data.yaml
> +          rm -rf data/
I removed/reverted the `rm` command because removing `--cached` also deletes off disk.

2024-11-04 18:58 UTC, sprt requested changes
Just a couple more comments. Very close, thanks!

2024-11-04 18:58 UTC, sprt commented on pages/index.js
> +        </div>``
```suggestion
        </div>
```

2024-11-04 18:58 UTC, sprt commented on .github/workflows/fetch-ci-nightly-data.yaml
> +          git rm -r data/
Let's revert to minimize the amount of changes, unless we have a strong reason to do this
```suggestion
          # overwrite the old data
```

2024-11-04 23:29 UTC, merged