Small enhancements
kata-containers/kata-containers.github.io pull request #20
Opened 2024-11-05 21:13 UTC by afinn12

## Changes
- Changed basePath in next.config.js
- Added win-dev/NODE_ENV=development
- Updated dev data to ../data/job_stats.json (instead of ../job_stats.json)
- Simplified weatherTemplate.js 
  - Removed getWeatherIcon
  - Removed console.assert()
  - Error check that idx is not > icons.length

## Testing
[x] Tested in dev
[x] Tested in prod
in prod (using build/start): 
![image](https://github.com/user-attachments/assets/2f587e57-fa07-48fe-aacb-e0e831b67e2c)

2024-11-06 17:22 UTC, a1icja requested changes
Definitely some changes that need to be made, but they're all minor

2024-11-06 17:22 UTC, a1icja commented on .github/workflows/deploy.yml
Some context on the changes in this file:

This allows for us to have a staging instance by hosting in another repo without constantly modifying the code

2024-11-06 17:22 UTC, a1icja commented on components/weatherTemplate.js
> +    // console.assert(fail_rate == 1.0);
```suggestion
```

2024-11-06 17:22 UTC, a1icja commented on components/weatherTemplate.js
> +        // src={`${basePath}/${icon}`}
```suggestion
```

2024-11-06 17:22 UTC, a1icja commented on next.config.js
> +  // basePath: process.env.NEXT_PUBLIC_BASE_PATH || "",
This goes hand in hand with the deploy script changes

```suggestion
  basePath: process.env.NEXT_PUBLIC_BASE_PATH || "",
```

2024-11-06 17:22 UTC, a1icja commented on package.json
> +    "win-dev": "next dev",
Did we ever figure out how to set an env var dynamically in Windows?

2024-11-06 17:22 UTC, a1icja commented on pages/index.js
> +        data = (await import("../data/job_stats.json")).default;
This needs to remain as is because of the README and .gitignore

```suggestion
        data = (await import("../job_stats.json")).default;
```

2024-11-06 17:38 UTC, afinn12 commented on package.json
> +    "win-dev": "next dev",
I'm using windows and when i run this, it appears to set the env var to automatically (the basePath is ""). 

Even running: NODE_ENV=development & next dev
doesn't work. It gives: "'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file."

I think it's fine as is.

2024-11-06 17:51 UTC, afinn12 commented on pages/index.js
> +        data = (await import("../data/job_stats.json")).default;
Actually, looking at this again.

Would it be bad to keep the data in /data and just adjust the readme?
Keeps files more organized, especially if more data/fetch scripts are added later. 
Not a big change.

2024-11-07 20:52 UTC, sprt requested changes
Thanks @afinn12! I left a few comments/questions.

For this PR, can you edit your commit message and list the same bullet points you listed in the PR description?

In future PRs (not this one), each such bullet point should be an individual commit (roughly, use your best judgement to split up into logical changes) to facilitate review. Potentially also split up into different PRs, as you'll notice that the review-correction cycle can delay merging: if you have multiple PRs, you can at least prioritize the features/PRs you want to get merged.

Crafting PRs is tricky! More info on this process here: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#best-practices-for-patches
And some examples:
https://github.com/kata-containers/kata-containers/pull/10466/commits
https://github.com/kata-containers/kata-containers/pull/10038/commits

2024-11-07 20:52 UTC, sprt commented on .github/workflows/deploy.yml
> +        uses: actions/deploy-pages@v4
Let's leave the trailing newline here. You probably need to configure your editor.

2024-11-07 20:52 UTC, sprt commented on .github/workflows/deploy.yml
> +  NEXT_PUBLIC_BASE_PATH: ${{ vars.NEXT_PUBLIC_BASE_PATH }}
Could you explain why we need this?

2024-11-07 20:52 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +main();
```suggestion
main();

```

2024-11-07 20:52 UTC, sprt commented on README.md
> +    TOKEN=token <GITHUB_PAT_OR_OTHER_VALID_TOKEN>
Could you document or link to instructions on how to obtain this token?

2024-11-07 20:52 UTC, sprt commented on .gitignore
> +!/localata/.gitkeep
I don't see `localData/` committed here?

2024-11-07 20:52 UTC, sprt commented on README.md
> +
```suggestion
```

2024-11-07 20:52 UTC, sprt commented on README.md
>     npm run dev
```suggestion
   npm run dev # On Windows, run `npm run win-dev` instead.
```

2024-11-07 20:52 UTC, sprt commented on README.md
> +   node --require dotenv/config .\scripts\fetch-ci-nightly-data.js > localData\job_stats.json
```suggestion
   node --require dotenv/config scripts/fetch-ci-nightly-data.js > localData/job_stats.json
```

2024-11-07 20:52 UTC, sprt commented on README.md
> +   node --require dotenv/config .\scripts\fetch-ci-nightly-data.js > localData\job_stats.json
Instead of using `--require` here, please check if npm supports devDependencies, and if so let's install those dependencies earlier in the instructions.

2024-11-07 20:52 UTC, sprt commented on README.md
>  - **Fetch CI Nightly Data**:
Let's actually remove this entire Scripts section - it's redundant.

2024-11-07 20:52 UTC, sprt commented on next.config.js
> +}
```suggestion
}

```

2024-11-07 20:52 UTC, sprt commented on package.json
> +}
```suggestion
}

```

2024-11-07 20:52 UTC, sprt commented on README.md
> +   node --require dotenv/config .\scripts\fetch-ci-nightly-data.js > localData\job_stats.json
Ah just saw the package.json modification - is this flag required here then? Let's ensure `npm install` above installs the dev dependencies.

2024-11-07 20:52 UTC, sprt commented on pages/index.js
> +}
```suggestion
}

```

2024-11-07 20:52 UTC, sprt commented on components/weatherTemplate.js
> +};
```suggestion
};

```

2024-11-07 20:52 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +  }
Doesn't the previous code with `then()` already do error handling implictly? If so, we should switch back to that. Same in the function below.

2024-11-07 20:52 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +  // const contexts = json?.protection?.required_status_checks?.contexts;
```suggestion
```

2024-11-07 20:52 UTC, sprt commented on pages/index.js
> +        data = (await import("../localData/job_stats.json")).default;
Why this change? What does it facilitate? Is it just to have the JSON in a separate folder?

2024-11-08 19:53 UTC, a1icja commented on .github/workflows/deploy.yml
> +  NEXT_PUBLIC_BASE_PATH: ${{ vars.NEXT_PUBLIC_BASE_PATH }}
This makes it easier for people to fork the repo and deploy with GitHub pages such that they can have a preview for their PR. Take the repo we're merging this PR in from.

This is the repo-wide GH Actions variable:
![image](https://github.com/user-attachments/assets/3d5d3841-92ed-47d7-bc3f-2e1fca645205)

And it can be accessed here: [https://a1icja.github.io/kata-containers.github.io/](https://a1icja.github.io/kata-containers.github.io/)

However, we don't want that for this repo since it doesn't have a basePath: [https://kata-containers.github.io](https://kata-containers.github.io). If the variable is undefined, it will use `""` for the basePath and assume the site is being served at root.

It's inconsequential for upstream, but it makes it much easier to have a PR preview in another repo so that nobody needs to clone the fork and run it locally.

2024-11-08 21:47 UTC, afinn12 commented on README.md
> +   node --require dotenv/config .\scripts\fetch-ci-nightly-data.js > localData\job_stats.json
For me, I needed to install the dev dependencies and have the --require. 
![image](https://github.com/user-attachments/assets/929a2df9-4037-4868-9bb0-663b846850e5)

2024-11-08 21:47 UTC, afinn12 commented on scripts/fetch-ci-nightly-data.js
> +  }
It will handle the error, but this adds a message for debugging. The message will also appear in workflows. 
Before:
![image](https://github.com/user-attachments/assets/d3c662bb-fe5e-486c-9a1d-04d46e1c46f8)
(does not indicate the fetch failed b/c it was unauthorized (no token). Instead, the code proceeds until this error is thrown)

After:
![image](https://github.com/user-attachments/assets/1adf4d5d-4369-4396-acd6-1479b7f4912b)

2024-11-11 17:41 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +  }
Got it. I would extra common code into a separate function we can reuse, to avoid duplication.

2024-11-11 17:46 UTC, sprt commented on .github/workflows/deploy.yml
> +  NEXT_PUBLIC_BASE_PATH: ${{ vars.NEXT_PUBLIC_BASE_PATH }}
Please document this flow in the readme

2024-11-11 17:46 UTC, sprt commented on README.md
> +    TOKEN=token <GITHUB_PAT_OR_OTHER_VALID_TOKEN>
Do you know rougly how close we are to the new limit?

2024-11-11 17:53 UTC, sprt commented on README.md
> +   node --require dotenv/config .\scripts\fetch-ci-nightly-data.js > localData\job_stats.json
Got it. Doesn't it make more sense instead to add a `require()` statement directly into the JS file?

2024-11-12 17:01 UTC, sprt commented on .gitignore
> +!/localata/.gitkeep
On second thought it's better to create this folder as part of the script, and gitignore the entire folder.

2024-11-18 19:25 UTC, afinn12 commented on README.md
> +    TOKEN=token <GITHUB_PAT_OR_OTHER_VALID_TOKEN>
Current fetch count is 22 when I ran the script (very below limit, will increase with reruns)

2024-11-20 17:30 UTC, sprt commented on scripts/fetch-ci-nightly-data.js
> +require('dotenv').config();
Need to guard this for GHA

2024-11-22 17:02 UTC, sprt approved these changes

2024-11-22 17:02 UTC, sprt commented on README.md
> +   node scripts/fetch-ci-nightly-data.js > localData/job_stats.json
I'll do this in another PR.
```suggestion
   node --require dotenv/config scripts/fetch-ci-nightly-data.js > localData/job_stats.json
```

2024-11-22 17:02 UTC, sprt commented on .github/workflows/deploy.yml
> +        run: NEXT_PUBLIC_BASE_PATH=${{ env.NEXT_PUBLIC_BASE_PATH }} ${{ steps.detect-package-manager.outputs.runner }} next build
We don't need a condition here. I'll fix this in another PR.

2024-11-22 17:03 UTC, merged