Required filter
kata-containers/kata-containers.github.io pull request #21
Opened 2024-11-05 21:23 UTC by afinn12

Without Filter:
![image](https://github.com/user-attachments/assets/0f8ce60d-66b9-4b91-b9b2-bd4cec2b380d)

With Filter:
![image](https://github.com/user-attachments/assets/388ef643-7457-4191-b147-09d56d910304)

2024-11-06 17:24 UTC, a1icja requested changes
Minor changes, but otherwise nice!

2024-11-06 17:24 UTC, a1icja commented on pages/index.js
> +
```suggestion

```

2024-11-06 17:24 UTC, a1icja commented on pages/index.js
> +        data = (await import("../data/job_stats.json")).default;
Please leave this alone as per #20 

```suggestion
        data = (await import("../job_stats.json")).default;
```

2024-11-22 20:18 UTC, sprt approved these changes

2024-11-22 20:24 UTC, merged