dashboard: Fetch data whenever a PR is merged into main
kata-containers/kata-containers.github.io pull request #24
Opened 2024-11-06 00:40 UTC by afinn12

**Context:**
If we merge a PR to main that assumes that new data is required (e.g. the PR runs view feature), the website will be updated immediately, but the data will take up to 24 hours to refresh. However, we need the new data.

**Solution:** 
On any push to the main branch, the fetch workflow will be triggered (includes merges).

2024-11-06 01:02 UTC, sprt commented
I thought of doing this but decided against it: we risk needlessly going over the GH rate limit in case we merge a bunch of PRs that don't affect the data schema.

But, can we implement this in a way that it only triggers the workflow if the fetching script is modified? If we do that, do you see any potential issue with that approach?

2024-11-06 01:03 UTC, sprt commented
Also if you decide to pursue this PR, please only keep the commit that's relevant to the title, so we minimize the PR size.

2024-11-06 01:51 UTC, afinn12 commented
Should be implemented with your suggested changes.

2024-11-06 19:26 UTC, sprt requested changes

2024-11-06 19:26 UTC, sprt commented on .github/workflows/fetch-ci-nightly-data.yaml
> +      # - '.github/workflows/fetch-ci-nightly-data.yaml'
Let's do this as discussed in the meeting. We can add the other script in the PR that introduces it.
```suggestion
      - 'scripts/fetch-data-nightly.js'
      - '.github/workflows/fetch-ci-nightly-data.yaml'
```

2024-11-06 19:27 UTC, sprt commented
@afinn12 Can you fix the commit message check and also include "Fixes: #7" in your commit message so the issue is automatically closed?

2024-11-07 13:54 UTC, sprt approved these changes

2024-11-07 13:54 UTC, merged