dashboard: Add Maintainers List
kata-containers/kata-containers.github.io pull request #29
Opened 2024-11-07 20:11 UTC by afinn12

2024-11-13 16:41 UTC, sprt commented
To update UI as such:
```
Maintainers:
Rust: NameA, NameB
S390x: NameC, NameD NameA
```

2024-11-18 20:08 UTC, afinn12 commented
## Description
- Maintainers are listed by group with a drop-down panel displaying their contact information. Github/slack are links. 
![image](https://github.com/user-attachments/assets/8e0db86a-aabb-4185-9ee2-753ad5bbc13b)

- Name's won't split, but will still wrap. 
![image](https://github.com/user-attachments/assets/6d166414-1a72-460f-8c3a-d85b087c564d)

2024-11-18 23:57 UTC, a1icja commented on pages/index.js
> +  };
Should probably revert this

2024-11-18 23:57 UTC, a1icja commented on pages/index.js
> +        <div className="mt-4 p-2 bg-gray-300 w-full">
This is a really long section. Any way to break this up?

2024-11-19 19:06 UTC, sprt requested changes

2024-11-19 19:06 UTC, sprt commented on maintainers.yml
> +        # slackid: "U0369UMM69M"
Let's remove these comments.

2024-11-19 19:06 UTC, sprt commented on maintainers.yml
> +        group: "arch-s390x"
The `group` key should be at the same level as `regex`, not inside `owners`.

2024-11-19 19:35 UTC, AdithyaKrishnan commented on maintainers.yml
> +  - regex: ".*qemu-(sev|snp).*"
Hey @afinn12 ! Thanks a ton for your contributions.
In one of our CoCo CI meetings, we decided to take ownership of the ovmf, ovmf-sev and snp-experimental workflows as well in addition to our SEV and SEV-SNP workflows
Could you please include the additional ones too under our names?
I guess ```.*(qemu-(sev(-snp)?|snp(-experimental)?)|ovmf(-sev)?).*``` should work

2024-11-19 20:27 UTC, afinn12 commented on maintainers.yml
> +  - regex: ".*qemu-(sev|snp).*"
Yes, will the group name still just be "amd" for all of this?

2024-11-19 20:31 UTC, AdithyaKrishnan commented on maintainers.yml
> +  - regex: ".*qemu-(sev|snp).*"
Yes, preferably "AMD"

2024-11-19 20:40 UTC, AdithyaKrishnan approved these changes

2024-11-20 09:51 UTC, stevenhorsman approved these changes
I think this looks fine as an initial version, that we can interatively improve. Thanks!

2024-11-22 20:01 UTC, sprt approved these changes

2024-11-22 20:12 UTC, merged